/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuideStatutesOfLimitationsRouteImport } from './routes/guide.statutes-of-limitations'
import { Route as CardSlugRouteImport } from './routes/card.$slug'
import { Route as ApiPublicHooksGenerateCardsRouteImport } from './routes/api/public/hooks/generate-cards'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideStatutesOfLimitationsRoute =
  GuideStatutesOfLimitationsRouteImport.update({
    id: '/guide/statutes-of-limitations',
    path: '/guide/statutes-of-limitations',
    getParentRoute: () => rootRouteImport,
  } as any)
const CardSlugRoute = CardSlugRouteImport.update({
  id: '/card/$slug',
  path: '/card/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksGenerateCardsRoute =
  ApiPublicHooksGenerateCardsRouteImport.update({
    id: '/api/public/hooks/generate-cards',
    path: '/api/public/hooks/generate-cards',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/card/$slug': typeof CardSlugRoute
  '/guide/statutes-of-limitations': typeof GuideStatutesOfLimitationsRoute
  '/api/public/hooks/generate-cards': typeof ApiPublicHooksGenerateCardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/card/$slug': typeof CardSlugRoute
  '/guide/statutes-of-limitations': typeof GuideStatutesOfLimitationsRoute
  '/api/public/hooks/generate-cards': typeof ApiPublicHooksGenerateCardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/card/$slug': typeof CardSlugRoute
  '/guide/statutes-of-limitations': typeof GuideStatutesOfLimitationsRoute
  '/api/public/hooks/generate-cards': typeof ApiPublicHooksGenerateCardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/card/$slug'
    | '/guide/statutes-of-limitations'
    | '/api/public/hooks/generate-cards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/card/$slug'
    | '/guide/statutes-of-limitations'
    | '/api/public/hooks/generate-cards'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/card/$slug'
    | '/guide/statutes-of-limitations'
    | '/api/public/hooks/generate-cards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CardSlugRoute: typeof CardSlugRoute
  GuideStatutesOfLimitationsRoute: typeof GuideStatutesOfLimitationsRoute
  ApiPublicHooksGenerateCardsRoute: typeof ApiPublicHooksGenerateCardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/statutes-of-limitations': {
      id: '/guide/statutes-of-limitations'
      path: '/guide/statutes-of-limitations'
      fullPath: '/guide/statutes-of-limitations'
      preLoaderRoute: typeof GuideStatutesOfLimitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$slug': {
      id: '/card/$slug'
      path: '/card/$slug'
      fullPath: '/card/$slug'
      preLoaderRoute: typeof CardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/generate-cards': {
      id: '/api/public/hooks/generate-cards'
      path: '/api/public/hooks/generate-cards'
      fullPath: '/api/public/hooks/generate-cards'
      preLoaderRoute: typeof ApiPublicHooksGenerateCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CardSlugRoute: CardSlugRoute,
  GuideStatutesOfLimitationsRoute: GuideStatutesOfLimitationsRoute,
  ApiPublicHooksGenerateCardsRoute: ApiPublicHooksGenerateCardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
