INSERT INTO public.law_cards (slug, title, country, category, summary, full_explanation, rights, what_to_do, search_terms)
VALUES (
  'common-law-marriage-states',
  'Common law marriage: which US states (and countries) recognize it',
  'usa',
  'family',
  'Common law marriage lets a couple be treated as legally married without a license or ceremony — but only a handful of US states still allow new ones, and the requirements differ in each.',
  E'A "common law marriage" is a marriage that becomes legally valid because a couple lives together, presents themselves as married, and intends to be married — without a marriage license or formal ceremony. Once it is valid, the couple has the same legal status as any other married couple, including for divorce, inheritance, taxes, and benefits.\n\nIn the United States, most states stopped recognizing new common law marriages in the 20th century. Only a small group still allow couples to form one today:\n\n- Colorado\n- Iowa\n- Kansas\n- Montana\n- Oklahoma (limited / disputed for marriages after 1998)\n- Rhode Island\n- Texas (called "informal marriage")\n- Utah (court order required)\n- District of Columbia\n\nNew Hampshire recognizes common law marriage only for inheritance purposes after one partner dies.\n\nA few states (such as Alabama, Georgia, Idaho, Ohio, Pennsylvania, and South Carolina) abolished common law marriage at some point but still recognize older ones formed before the cut-off date.\n\nEvery other US state will still recognize a common law marriage that was validly created in one of the states above — this is called "full faith and credit." So a couple who became common-law married in Texas and then moved to California is treated as married in California.\n\nThe usual requirements are: (1) both partners are adults and legally free to marry, (2) they agree they are married now (not "someday"), (3) they live together, and (4) they hold themselves out publicly as a married couple — for example, using the same last name, calling each other husband/wife/spouse, filing joint taxes, or naming each other on insurance.\n\nOutside the US, "common law partner" can mean something different. Countries such as Canada, Australia, and parts of the UK use the term for unmarried cohabiting couples who get some — but not all — of the rights of married couples after living together for a set period.',
  E'- If you meet your state''s requirements, you have the same legal rights as any other married couple, including spousal inheritance, health-care decisions, and divorce protections.\n- A common law marriage validly formed in one US state must be recognized by every other US state.\n- You generally cannot "common law divorce" — ending a common law marriage requires a formal divorce in court.\n- A surviving common law spouse can usually claim Social Security survivor benefits and inheritance under state intestacy law.',
  E'- Check your specific state''s rules — requirements and cut-off dates vary, and a few states only count common law marriages formed before a certain year.\n- Keep written evidence that you held yourselves out as married: joint tax returns, joint leases or mortgages, shared bank accounts, beneficiary designations, and statements to family or employers.\n- If you want certainty (for immigration, insurance, or estate planning), consider getting a regular marriage license — it removes any dispute about whether the marriage exists.\n- To end a common law marriage, file for divorce in family court the same way a ceremonially married couple would.\n- For high-stakes situations (inheritance disputes, immigration, custody), talk to a family-law attorney in your state.',
  'common law marriage, common law marriage states, what states have common law marriage, common law marriage requirements, informal marriage texas, common law spouse, common law partner'
)
ON CONFLICT (slug) DO NOTHING;